# Generated by Django 4.2.3 on 2023-07-28 12:05

from django.db import migrations, models
import librarians.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.BigIntegerField(unique=True)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll_number', models.CharField(max_length=15)),
                ('isbn', models.BigIntegerField()),
                ('issued_date', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField(default=librarians.models.expiry)),
            ],
        ),
    ]
